version: '2.1'
services:
  hn_manticore_default:
    build:
      context: .
      dockerfile: Dockerfile_manticore_default
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9306
    container_name: "hn_manticore_default"
    mem_limit: 734003200
    mem_swappiness: 0
  hn_manticore_mmap:
    build:
      context: .
      dockerfile: Dockerfile_manticore_mmap
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9306
    container_name: "hn_manticore_mmap"
    mem_limit: 734003200
    mem_swappiness: 0
  hn_test:
    build:
      context: test
    container_name: "hn_test_file_vs_mmap"

