version: '2.2'
services:
  hn_manticore_default:
    build:
      context: .
      dockerfile: Dockerfile_manticore_default
    ports:
      - "9306:9306"
    expose:
      - 9306
    container_name: "hn_manticore_default"
  hn_manticore_mlock:
    build:
      context: .
      dockerfile: Dockerfile_manticore_mlock
    ports:
      - "9307:9306"
    expose:
      - 9306
    container_name: "hn_manticore_mlock"
  hn_test:
    build:
      context: test
    container_name: "hn_test_file_vs_mlock"

